TASK_LIST/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("",include('users.urls')),
    path("", include("todo.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path

from . import views


app_name = 'todo'
urlpatterns = [
    path("", views.home, name="home"),
    path("tasks/", views.TaskList.as_view(), name="tasks"),
    path("tasks/<int:pk>/", views.TaskDetail.as_view(), name="task_detail"),
    path("tasks/create/", views.TaskCreate.as_view(), name="task_create"),
    path("tasks/<int:pk>/update/", views.TaskUpdate.as_view(), name="task_update"),
    path("task/<int:pk>/delete/", views.TaskDelete.as_view(), name="task_delete"),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ["completed"]

todo/views.py
from typing import Any
from django.db import models
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Task

# Create your views here.
def home(request):
    return render(request, 'home.html')


class TaskList(LoginRequiredMixin, generic.ListView):
    model = Task
    context_object_name = 'tasks'
    
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class TaskDetail(LoginRequiredMixin, generic.DetailView):
    model = Task
    context_object_name = 'task'
    
    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class TaskCreate(LoginRequiredMixin, generic.CreateView):
    model = Task
    fields = ['title', 'description']
    success_url = reverse_lazy('todo:tasks')

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.user = self.request.user
        messages.add_message(self.request, messages.SUCCESS, 'Task created!')
        return super().form_valid(form)
    
    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class TaskUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Task
    fields = ['title', 'description', 'completed']
    success_url = reverse_lazy('todo:tasks')

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        messages.add_message(self.request, messages.SUCCESS, 'Task updated!')
        return super().form_valid(form)
    
    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class TaskDelete(LoginRequiredMixin, generic.DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('todo:tasks')

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        messages.add_message(self.request, messages.SUCCESS, 'Task deleted!')
        return super().form_valid(form)
    
    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)

todo/templates/todo/task_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="center">
	<form method="post" class="card">
		{% csrf_token %}

		<h2>Delete Task</h2>
		<p>Are you sure to delete task:</p>
        <p><strong>{{ task }}</strong></p>
		<p class="form-buttons">
			<input type="submit" class="btn btn-primary" value="Delete">
			<a href="{% url 'todo:tasks'%}" class="btn btn-outline">Cancel</a>
		</p>
	</form>
</div>

{%endblock content%}

<!-- 
	The DeleteView page displayed to a GET request uses a template_name_suffix of '_confirm_delete'.
	Thus, this template name have to be task_confirm_delete.html.
-->

todo/templates/todo/task_detail.html
{% extends 'base.html' %}

{% block content %}

 <article class="task">
	<header>
		<h2>{{ task.title }}</h2>
		<span class="badge {% if task.completed %} badge-completed {% else %} badge-pending {% endif %}">
			{% if task.completed %} Completed {% else %} Pending {% endif %}
		</span>
	</header>
	<p>{{ task.description }}</p>
</article>

{%endblock content%}

todo/templates/todo/task_form.html
{% extends 'base.html' %}

{% block content %}

<div class="center">
	<form method="post" novalidate class="card">
	 	{% csrf_token %}
        
	 	<h2>{% if task %} Update {% else %} Create {% endif %} Task</h2>
		{% for field in form %}
			{% if field.name == 'completed' %}
				<p>
					{{ field.label_tag }}
					{{ field }}
				</p>
				{% if field.errors %}
	        		<small class="error">{{ field.errors|striptags  }}</small> 
	        	{% endif %}
			{% else %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small class="error">{{ field.errors|striptags  }}</small> 
	        	{% endif %}
	        {% endif %}
		{% endfor %}
		
		<div class="form-buttons">
			<input type="submit" value="Save" class="btn btn-primary"/>
			<a href="{% url 'todo:tasks' %}" class="btn btn-outline">Cancel</a>
		</div>
	</form>
</div>

{% endblock content %}

todo/templates/todo/task_list.html
{% extends 'base.html' %}

{% block content %}

<div class="center">
	<h2>My Todo List</h2>
	{% if tasks %}
	<ul class="tasks">
		{% for task in tasks %}
			<li><a href="{% url 'todo:task_detail' task.id %}" class="{% if task.completed %}completed{% endif %}">{{ task.title }}</a> 
				<div  class="task-controls">
				 	<a href="{% url 'todo:task_delete' task.id %}"><i class="bi bi-trash"></i> </a>
					<a href="{% url 'todo:task_update' task.id %}"><i class="bi bi-pencil-square"></i></a>
		        </div>
		    </li>
		{% endfor %}
	{% else %}
		<p>😎Yeah~ you have no pending tasks!🎉</p>
        <a href="{% url 'todo:task_create' %}">Creat task</a>
	{% endif %}
	</ul>
</div>

{% endblock content %}