TASK_LIST/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("",include('users.urls')),
    path("", include("todo.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path

from . import views


app_name = 'todo'
urlpatterns = [
    path("", views.home, name="home"),
    path("tasks/", views.TaskList.as_view(), name="tasks"),
    path("tasks/<int:pk>/", views.TaskDetail.as_view(), name="task_detail"),
    path("tasks/create/", views.TaskCreate.as_view(), name="task_create"),
    path("tasks/<int:pk>/update/", views.TaskUpdate.as_view(), name="task_update"),
    path("task/<int:pk>/delete/", views.TaskDelete.as_view(), name="task_delete"),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import reverse_lazy

from . import views
 
app_name = 'users'
urlpatterns = [
    path('login/', views.MyLoginView.as_view(redirect_authenticated_user=True), name='login'),
    
    path('logout/', LogoutView.as_view(next_page='users:login'), name='logout'),
    
    path('signup/', views.SignupView.as_view(), name='signup'),
    
    path('password_reset/', 
         PasswordResetView.as_view(template_name='users/password_reset.html', email_template_name='users/password_reset_email.html', success_url=reverse_lazy('users:password_reset_done')), 
         name='password_reset'),
    
    path('password_reset/done/', 
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), 
         name='password_reset_done'),
    
    path('password_reset_confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url=reverse_lazy("users:password_reset_complete")), 
         name='password_reset_confirm'),
    
    path('password_reset/complete/', 
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), 
         name='password_reset_complete'),
    
    path('profile/', views.MyProfileView.as_view(), name='profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Create your models here.
class Profile(models.Model):
    # each user has a profile and each profile belongs to a user. 
    # Therefore, the relationship between the User model and the 
    # Profile model is one-to-one.
    # If a User is deleted, the Profile associated with the User
    # is also deleted, thus indicates on_delete=models.CASCADE
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='avatar.jpg', upload_to='profile_avatars')
    
    def __str__(self) -> str:
        return f'{self.user.username} Profile'
    
    def save(self, *args, **kwargs):
        # save the profile first
        super().save(*args, **kwargs)
        
        img = Image.open(self.avatar.path)
        # resize the iamge
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            # create a thumbnail
            img.thumbnail(output_size)
            img.save(self.avatar.path)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Profile

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username',  'email', 'password1', 'password2', )


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']

        
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar']

users/views.py
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login
from django.urls import reverse_lazy
from django.views import generic, View
from django.contrib import messages
from django.shortcuts import render, redirect

from . import forms 


class MyLoginView(LoginView):
    # The template_name of LoginView defaults to 'registration/login.html'. 
    # So here we need to set it to 'users/login.html'
    template_name = 'users/login.html'
    fields = '__all__'
    redirect_authenticated_user = True
    
    def get_success_url(self):
        return reverse_lazy('todo:tasks') 
    
    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, 'Invalid username or password')
        return self.render_to_response(self.get_context_data(form=form))


class SignupView(generic.FormView):
    template_name = 'users/signup.html'
    form_class = forms.SignupForm
    success_url = reverse_lazy('todo:tasks')
    redirect_authenticated_user = True
    
    def form_valid(self, form):
        user = form.save()
        
        if user:
            login(self.request, user)
        
        return super().form_valid(form)


class MyProfileView(LoginRequiredMixin, View):
    def get(self, request):
        user_form = forms.UserUpdateForm(instance=request.user)
        profile_form = forms.ProfileUpdateForm(instance=request.user.profile)
        
        context = {
            'user_form': user_form,
            'profile_form': profile_form
        }
        
        return render(request, 'users/profile.html', context=context)
    
    def post(self, request):
        user_form = forms.UserUpdateForm(request.POST, instance=request.user)
        profile_form = forms.ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            
            messages.add_message(request, messages.SUCCESS, 'Your profile has been updated!')
            
            return redirect('users:profile')
        else:
            context = {
                'user_form': user_form,
                'profile_form': profile_form
            }
            
            messages.add_message(request, messages.ERROR, 'Error updating your profile')
        
            return render(request, 'users/profile.html', context=context)
    

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
  <div class="center">
	  <form method="post" class="card" novalidate>
	  	{% csrf_token %}

	    <h2 class="text-center">Sign in to your account</h2>
		{% for field in form %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags }}</small> 
	        	{% endif %}
		{% endfor %}		
		<input type="submit" value="Sign in" class="btn btn-primary full-width">
		<hr>
		<small><p class="text-center">Forgot your password? <a href="{% url 'users:password_reset' %}">Reset Password</a></p></small>
		<small><p class="text-center">No account? <a href="{% url 'users:signup'%}">Create one</a></p></small>
	</form>
</div>

{% endblock %}

users/templates/users/password_reset.html
{% extends 'base.html' %}

{% block content %}
<div class="center">
	<form method="post" class="card">
		{% csrf_token %}

	    <h2 class="text-center">Reset Password</h2>
		{% for field in form %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small> 
	        	{% endif %}
		{% endfor %}
		<div class="form-buttons">
			<input type="submit" value="Send" class="btn btn-primary">
			<a href="{%url 'users:login' %}"  class="btn btn-outline">Cancel</a>
		</div>
	</form>
	</div>

{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}

<div class="card center">
	<p>Your password has been changed successfully. Please <a href="{% url 'users:login' %}">Sign in</a></p>
</div>
 	
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}

<div class="center">
	<form method="post" class="card">
	    {% csrf_token %}

	    <h2>Password Reset</h2>
	    {% for field in form %}
            {{ field.label_tag }} 
            {{ field }}
            {% if field.errors %}
                <small>{{ field.errors|striptags  }}</small> 
            {% endif %}
	    {% endfor %}
        <div>
	        <button type="submit" class="btn btn-primary">Reset Password</button>
        </div>
	</form>
</div>

{% endblock content %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

<div class="center card">
	<h2>Reset Password</h2>
	<p>Please check your inbox and follow the instruction to reset your password.</p>
	<br>
	<p>Back to <a href="{% url 'users:login' %}">sign in</a></p>
</div>

{% endblock content %}

users/templates/users/password_reset_email.html
<p>Hi</p>

<p>You're receiving this email because you requested a password reset for your user account at {{domain}}/</p>

<p>Please click the following link to reset your password:</p>

{{ protocol }}://{{ domain }}{% url "users:password_reset_confirm" uidb64=uid token=token %}

<p>Thanks</p>
<p>Todo App Team</p>

users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="center">
    <form method="post" enctype="multipart/form-data" class="card">
        {% csrf_token %}
        {% if user.profile %}
            <img src="{{user.profile.avatar.url}}" alt="{{ user.username }}" class="avatar" accept=".jpg,.jpeg,.png"/>
        {% endif %}
        <h2 class="text-center">{{ user.username | title }}</h2>
        <p class="text-center"><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
        <hr>
        <label for="email">Email Address:</label>
        <input type="email" name="email" id="email" value="{{ user.email }}">
        <label for="avatar">Avatar:</label>
        <input type="file" name="avatar" id="avatar">
        <button type="submit" class="btn btn-primary full-width">Update Profile</button>
    </form>
</div>

{% endblock content %}

users/templates/users/signup.html
{% extends 'base.html' %}

{% block content %}

	<div class="center">
	  <form method="post" novaldiate class="card">
	  	{% csrf_token %}

	    <h2 class="text-center">Create Todo Account</h2>
		{% for field in form %}
            {{ field.label_tag }} 
            {{ field }}
            {% if field.errors %}
                <small class="error">{{ field.errors|striptags  }}</small> 
            {% endif %}
		{% endfor %}
		<input type="submit" value="Sign up" class="btn btn-primary full-width">
		<hr>
		<small><p class="text-center">Already a user? <a href="{% url 'users:login' %}">Sign in</a></p></small>
		</form>
	</div>

{% endblock content %}