TASK_LIST/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("",include('users.urls')),
    path("", include("todo.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path

from . import views


app_name = 'todo'
urlpatterns = [
    path("", views.home, name="home"),
    path("tasks/", views.TaskList.as_view(), name="tasks"),
    path("tasks/<int:pk>/", views.TaskDetail.as_view(), name="task_detail"),
    path("tasks/create/", views.TaskCreate.as_view(), name="task_create"),
    path("tasks/<int:pk>/update/", views.TaskUpdate.as_view(), name="task_update"),
    path("task/<int:pk>/delete/", views.TaskDelete.as_view(), name="task_delete"),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import reverse_lazy

from . import views
 
app_name = 'users'
urlpatterns = [
    path('login/', views.MyLoginView.as_view(redirect_authenticated_user=True), name='login'),
    
    path('logout/', LogoutView.as_view(next_page='users:login'), name='logout'),
    
    path('signup/', views.SignupView.as_view(), name='signup'),
    
    path('password_reset/', 
         PasswordResetView.as_view(template_name='users/password_reset.html', email_template_name='users/password_reset_email.html', success_url=reverse_lazy('users:password_reset_done')), 
         name='password_reset'),
    
    path('password_reset/done/', 
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), 
         name='password_reset_done'),
    
    path('password_reset_confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url=reverse_lazy("users:password_reset_complete")), 
         name='password_reset_confirm'),
    
    path('password_reset/complete/', 
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), 
         name='password_reset_complete'),
    
    path('profile/', views.MyProfileView.as_view(), name='profile'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        <title>Todo List</title>
    </head>
    <body>
        <header class="header">
            <div class="container">
                <a href="{% url 'todo:home' %}" class="logo">Todo</a>
                <nav class="nav">
                    <a href="{% url 'todo:home' %}"><i class="bi bi-house-fill"></i> Home</a>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'todo:tasks' %}"><i class="bi bi-list-task"></i> My Tasks</a>
                        <a href="{% url 'todo:task_create' %}"><i class="bi bi-plus"></i> Create Task</a>
                        <a href="{% url 'users:profile' %}" title="Update profile">Hi {{ request.user | title }}</a>
                        <a href="{% url 'users:logout' %}"><i class="bi bi-box-arrow-right"></i> Sign out</a>
                    {% else %}
                        <a href="{% url 'users:login' %}" class="btn btn-outline">Sign in</a>
                        <a href="{% url 'users:signup' %}" class="btn btn-primary">Sign up</a>
                    {% endif %}
                </nav>
            </div>
        </header>
        <main>
            <div class="container">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% block content %}
                {% endblock content%}
            </div>
        </main>
        <footer class="footer">
            <div class="container">
                <small><p>&copy; Copyright {% now "Y" %}  by <a href="https://www.pythontutorial.net"> Python Tutorial</a></p></small>
            </div>
        </footer>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
	<section class="feature">
		<div class="feature-content">
			<h1>Todo</h1>
			<p>Todo helps you more focus, either work or play.</p>	
			<a class="btn btn-primary cta" href="{% url 'users:signup' %}">Get Started</a>
		</div>
		<img src="{% static 'images/feature.jpg' %}" alt="" class="feature-image">
	</section>
{% endblock content %}